Repository CSC207-2022F-UofT/course-project-schedulize, pull requests merged in 2022-12, with the labels that each got.

#72 Create suggest password use case
  src/main/java/Main.java
  src/main/java/UI/CreateAccountUI.java
  src/main/java/entity_layer/PasswordSuggester.java
  src/main/java/entity_layer/RandomPasswordGenerator.java
  src/main/java/use_cases/suggest_password/PasswordSuggestionController.java
  src/main/java/use_cases/suggest_password/PasswordSuggestionInputBoundary.java
  src/main/java/use_cases/suggest_password/PasswordSuggestionInteractor.java
  src/test/java/SuggestPasswordUseCaseTests.java
  src/test/java/entity_layer/RandomPasswordGeneratorTests.java
Labels: enhancement

#85 71 conecting tasktree UI to backend
  src/main/java/UI/CurriculumDependentWindow.java
  src/main/java/UI/TaskDependentWindow.java
  src/main/java/task_tree_UI/TaskTreeUI.java
  src/main/java/tasktree_UI/TaskTreeUI.java
  src/main/java/use_cases/display_task_tree/DisplayTaskTreeController.java
  src/main/java/use_cases/display_task_tree/DisplayTaskTreeInputBoundary.java
  src/main/java/use_cases/display_task_tree/DisplayTaskTreeInteractor.java
  src/main/java/use_cases/display_task_tree/DisplayTaskTreeOutputBoundary.java
  src/main/java/use_cases/display_task_tree/DisplayTaskTreePresenter.java
  src/main/java/use_cases/display_task_tree/TaskDisplayModel.java
  src/main/java/use_cases/display_task_tree/TaskTreeDisplayModel.java
  src/main/java/use_cases/display_task_tree/TaskTreeUIInterface.java
Labels: enhancement

#83 Implemented Input-side Create Curriculum Use Case Classes
  src/main/java/use_cases/create_curriculum/CreateCurriculumController.java
  src/main/java/use_cases/create_curriculum/CreateCurriculumInteractor.java
  src/main/java/use_cases/create_curriculum/CurriculumModel.java
Labels: enhancement

#90 Implemented outgoing use case classes for CreateCurriculum
  src/main/java/use_cases/create_curriculum/CreateCurriculumPresenter.java
  src/main/java/use_cases/create_curriculum/DashboardUiInterface.java
Labels: enhancement

#99 87 subissue 32 create dashboard UI
  src/main/java/Main.java
  src/main/java/UI/LoginUI.java
  src/main/java/UI/WindowManager.java
  src/main/java/dashboardUI/TaskUI.java
  src/main/java/dashboard_ui/DashboardUI.form
  src/main/java/dashboard_ui/DashboardUI.java
  src/main/java/entity_layer/CommonSchedule.java
  src/main/java/entity_layer/Schedule.java
  src/main/java/task_creation_ui/CreateTaskUI.form
  src/main/java/task_creation_ui/CreateTaskUI.java
  src/main/java/task_display_ui/TaskUI.form
  src/main/java/task_display_ui/TaskUI.java
  src/main/java/task_display_ui/TaskUiController.java
  src/main/java/task_display_ui/TaskUiInputBoundary.java
  src/main/java/task_display_ui/TaskUiInteractor.java
  src/main/java/task_display_ui/TaskUiModel.java
  src/main/java/task_display_ui/TaskUiModelPresenter.java
  src/main/java/task_display_ui/TaskUiOutputBoundary.java
  src/main/java/task_display_ui/TaskUiViewInterface.java
  src/main/java/use_cases/display_curriculums/CurriculumsModel.java
  src/main/java/use_cases/display_curriculums/DisplayCurriculumsController.java
  src/main/java/use_cases/display_curriculums/DisplayCurriculumsInputBoundary.java
  src/main/java/use_cases/display_curriculums/DisplayCurriculumsInteractor.java
  src/main/java/use_cases/display_curriculums/DisplayCurriculumsInterface.java
  src/main/java/use_cases/display_curriculums/DisplayCurriculumsOutputBoundary.java
  src/main/java/use_cases/display_curriculums/DisplayCurriculumsPresenter.java
  src/test/java/task_display_ui/TaskUiTestInteractor.java
  src/test/java/task_display_ui/TaskUiTestPresenter.java
  src/test/java/task_display_ui/TaskUiTestView.java
  src/test/java/task_display_ui/TaskUiTests.java
Labels: enhancement

#94 Connect live saving during program lifetime
  src/main/java/Main.java
  src/main/java/UI/CommonWindowManager.java
  src/main/java/UI/LoginUI.java
  src/main/java/use_cases/save_user/SaveUserController.java
  src/main/java/use_cases/save_user/SaveUserInputBoundary.java
  src/main/java/use_cases/save_user/SaveUserInteractor.java
  src/test/java/UserSaveTests.java
Labels: bug, enhancement

#89 Add Task Use Case Tests
  src/main/java/use_cases/add_task/AddTaskUseCase.java
  src/test/java/add_task/AddTaskUseCaseTest.java
Labels: bug, enhancement

#92 71 conecting tasktree UI to backend
  src/main/java/Main.java
  src/main/java/UI/WindowManager.java
  src/main/java/dashboard_ui/DashboardUI.form
  src/main/java/dashboard_ui/DashboardUI.java
  src/main/java/task_tree_UI/TaskTreeUI.java
  src/main/java/use_cases/create_curriculum/CreateCurriculumOutputBoundary.java
  src/main/java/use_cases/create_curriculum/CreateCurriculumPresenter.java
  src/main/java/use_cases/display_task_tree/DisplayTaskTreeController.java
  src/main/java/use_cases/display_task_tree/DisplayTaskTreeInputBoundary.java
  src/main/java/use_cases/display_task_tree/DisplayTaskTreeInteractor.java
  src/main/java/use_cases/display_task_tree/DisplayTaskTreeOutputBoundary.java
  src/main/java/use_cases/display_task_tree/DisplayTaskTreePresenter.java
  src/main/java/use_cases/display_task_tree/TaskDisplayModel.java
  src/main/java/use_cases/display_task_tree/TaskTreeDisplayModel.java
  src/main/java/use_cases/display_task_tree/TaskTreeUIInterface.java
Labels: enhancement

#96 Fix resetTask method for uncompleteTask use case
  src/main/java/entity_layer/CommonTask.java
  src/main/java/entity_layer/CommonTaskTree.java
  src/main/java/entity_layer/Task.java
  src/test/java/entity_layer/CommonTaskTreeTests.java
Labels: bug, enhancement

#93 Create Task UI Implemented
  src/main/java/UI/CurriculumDependentWindow.java
  src/main/java/UI/TaskDependentWindow.java
  src/main/java/UI/WindowManager.java
  src/main/java/create_task_UI/CreateTaskUI.form
  src/main/java/create_task_UI/CreateTaskUI.java
Labels: enhancement

#79 Set Availability Use Case - Update to TimeBlockManager Update Algorithm + Tests + Refactoring
  src/main/java/set_availability/SetAvailabilityController.java
  src/main/java/set_availability/SetAvailabilityModel.java
  src/main/java/set_availability/SetAvailabilityOutputBoundary.java
  src/main/java/set_availability/SetAvailabilityPresenter.java
  src/main/java/set_availability/SetAvailabilityUseCase.java
  src/main/java/use_cases/set_availability/SetAvailabilityController.java
  src/main/java/use_cases/set_availability/SetAvailabilityInputBoundary.java
  src/main/java/use_cases/set_availability/SetAvailabilityOutputBoundary.java
  src/main/java/use_cases/set_availability/SetAvailabilityPresenter.java
  src/main/java/use_cases/set_availability/SetAvailabilityUseCase.java
  src/main/java/use_cases/set_availability/SetAvailabilityViewInterface.java
  src/test/java/use_cases/set_availability/SetAvailabilityTestingViewInterface.java
  src/test/java/use_cases/set_availability/SetAvailabilityTests.java
Labels: bug, enhancement

#104 Bug fix with the DashBoardUI and TaskTreeUI
  src/main/java/dashboard_ui/DashboardUI.java
  src/main/java/task_tree_UI/TaskTreeUI.java
Labels: bug

#98 Added design pattern documentation to readme
  README.md
Labels: documentation

#103 Added an interface for the CompleteTaskPresenter
  src/main/java/task_display_ui/TaskUI.java
  src/main/java/use_cases/complete_task/CompleteTaskPresenter.java
  src/main/java/use_cases/complete_task/CompleteTaskUiInterface.java
  src/test/java/complete_task/completeTaskUseCaseTest.java
Labels: enhancement

#69 Implemented a cleaner and more revised Availability Time Block UI
  src/main/java/Main.java
  src/main/java/dashboard_ui/DashboardUI.form
  src/main/java/dashboard_ui/DashboardUI.java
  src/main/java/time_manager_UI/DisplayAvailabilityTimeBlockUI.form
  src/main/java/time_manager_UI/DisplayAvailabilityTimeBlockUI.java
  src/main/java/time_manager_UI/SetAvailabilityUI.form
  src/main/java/time_manager_UI/SetAvailabilityUI.java
  src/main/java/time_manager_UI/TimeBlockManagerUI.form
  src/main/java/time_manager_UI/TimeBlockManagerUI.java
  src/main/java/use_cases/display_availability_timeblocks/AvailabilityUiInterface.java
  src/main/java/use_cases/display_availability_timeblocks/DisplayAvailabilityTimeBlockController.java
  src/main/java/use_cases/display_availability_timeblocks/DisplayAvailabilityTimeBlockInputBoundary.java
  src/main/java/use_cases/display_availability_timeblocks/DisplayAvailabilityTimeBlockInteractor.java
  src/main/java/use_cases/display_availability_timeblocks/DisplayAvailabilityTimeBlockModel.java
  src/main/java/use_cases/display_availability_timeblocks/DisplayAvailabilityTimeBlockOutputBoundary.java
  src/main/java/use_cases/display_availability_timeblocks/DisplayAvailabilityTimeBlockPresenter.java
  src/main/java/use_cases/set_availability/SetAvailabilityUseCase.java
  src/test/java/display_availability_time_blocks/displayAvailabilityTestCase.java
Labels: enhancement

#106 19 feature 31 create task UI
  src/main/java/Main.java
  src/main/java/UI/WindowManager.java
  src/main/java/task_display_ui/TaskUI.java
  src/main/java/task_display_ui/TaskUiModelPresenter.java
  src/main/java/task_display_ui/TaskUiOutputBoundary.java
  src/main/java/task_tree_UI/TaskTreeUI.java
  src/main/java/use_cases/display_curriculums/CurriculumsModel.java
  src/main/java/use_cases/display_curriculums/DisplayCurriculumsController.java
  src/main/java/use_cases/display_curriculums/DisplayCurriculumsInteractor.java
  src/main/java/use_cases/display_curriculums/DisplayCurriculumsPresenter.java
  src/test/java/task_display_ui/TaskUiTestPresenter.java
  src/test/java/task_display_ui/TaskUiTests.java
Labels: enhancement

#100 Uncomplete Task Method
  src/main/java/UI/task_UI/TaskUI.form
  src/main/java/UI/task_UI/TaskUI.java
  src/main/java/use_cases/complete_task/CompleteTaskController.java
  src/main/java/use_cases/complete_task/CompleteTaskInputBoundary.java
  src/main/java/use_cases/complete_task/CompleteTaskInteractor.java
  src/main/java/use_cases/complete_task/CompleteTaskOutputBoundary.java
  src/main/java/use_cases/complete_task/CompleteTaskPresenter.java
  src/test/java/use_cases/complete_task/CompleteTaskInteractorTest.java
Labels: enhancement
