Repository CSC207-2022F-UofT/course-project-schedulize, pull requests merged in 2022-11, with the labels that each got.

#26 9 subissue 11 backend skeleton
  src/main/java/entityLayer/CommonCurriculum.java
  src/main/java/entityLayer/CommonSchedule.java
  src/main/java/entityLayer/CommonTask.java
  src/main/java/entityLayer/CommonTaskTree.java
  src/main/java/entityLayer/CommonTimeBlock.java
  src/main/java/entityLayer/CommonTimeBlockManager.java
  src/main/java/entityLayer/CommonUser.java
  src/main/java/entityLayer/Curriculum.java
  src/main/java/entityLayer/Schedule.java
  src/main/java/entityLayer/Task.java
  src/main/java/entityLayer/TaskTree.java
  src/main/java/entityLayer/TimeBlock.java
  src/main/java/entityLayer/TimeBlockManager.java
  src/main/java/entityLayer/User.java
Labels: enhancement

#28 LoginUI and PathManager made
  Icons/acorn.png
  Icons/eye-close.png
  Icons/eye.png
  src/main/java/Config/PathManager.java
  src/main/java/UI/LoginUI.form
  src/main/java/UI/LoginUI.java
  src/main/java/tutorial/HelloWorld.java
  src/test/java/tutorial/HelloWorldTest.java
Labels: enhancement

#32 New User Registry UI
  src/main/java/UI/CentralWindow.java
  src/main/java/UI/CommonWindowManager.java
  src/main/java/UI/CreateAccountUI.form
  src/main/java/UI/CreateAccountUI.java
  src/main/java/UI/LoginUI.form
  src/main/java/UI/LoginUI.java
  src/main/java/UI/PasswordField.java
  src/main/java/UI/WindowManager.java
Labels: enhancement

#33 Implemented completeTask use case
  src/main/java/complete_task/completeTaskController.java
  src/main/java/complete_task/completeTaskInputBoundary.java
  src/main/java/complete_task/completeTaskOutputBoundary.java
  src/main/java/complete_task/completeTaskPresenter.java
  src/main/java/complete_task/completeTaskUseCase.java
Labels: enhancement

#40 Implemented Task Classes
  src/main/java/entityLayer/CommonTask.java
  src/main/java/entityLayer/Task.java
  src/main/java/entity_factories/CommonTaskFactory.java
  src/main/java/entity_factories/TaskFactory.java
  src/test/java/entityLayer/CommonTaskTests.java
Labels: enhancement

#43 Create new user registration use case
  src/main/java/UI/CentralWindow.java
  src/main/java/UI/CreateAccountUI.java
  src/main/java/UI/LoginUI.java
  src/main/java/UI/PasswordField.java
  src/main/java/UI/UserRegistrationController.java
  src/main/java/UI/UserRegistrationResponseFormatter.java
  src/main/java/UI/WindowManager.java
  src/main/java/complete_task/completeTaskController.java
  src/main/java/complete_task/completeTaskInputBoundary.java
  src/main/java/complete_task/completeTaskOutputBoundary.java
  src/main/java/complete_task/completeTaskPresenter.java
  src/main/java/complete_task/completeTaskUseCase.java
  src/main/java/config/PathManager.java
  src/main/java/config/UserStorage.java
  src/main/java/entity_factories/CommonTaskFactory.java
  src/main/java/entity_factories/TaskFactory.java
  src/main/java/entity_layer/CommonCurriculum.java
  src/main/java/entity_layer/CommonSchedule.java
  src/main/java/entity_layer/CommonTask.java
  src/main/java/entity_layer/CommonTaskTree.java
  src/main/java/entity_layer/CommonTimeBlock.java
  src/main/java/entity_layer/CommonTimeBlockManager.java
  src/main/java/entity_layer/CommonUser.java
  src/main/java/entity_layer/CommonUserFactory.java
  src/main/java/entity_layer/Curriculum.java
  src/main/java/entity_layer/Schedule.java
  src/main/java/entity_layer/Task.java
  src/main/java/entity_layer/TaskTree.java
  src/main/java/entity_layer/TimeBlock.java
  src/main/java/entity_layer/TimeBlockManager.java
  src/main/java/entity_layer/User.java
  src/main/java/entity_layer/UserFactory.java
  src/main/java/use_cases/user_registration/UserDataStoreGateway.java
  src/main/java/use_cases/user_registration/UserRegistrationError.java
  src/main/java/use_cases/user_registration/UserRegistrationInputBoundary.java
  src/main/java/use_cases/user_registration/UserRegistrationInteractor.java
  src/main/java/use_cases/user_registration/UserRegistrationPresenter.java
  src/main/java/use_cases/user_registration/UserRegistrationRequest.java
  src/main/java/use_cases/user_registration/UserRegistrationResponse.java
  src/test/java/UserRegistrationTests.java
  src/test/java/UserStorageTests.java
  src/test/java/entity_layer/CommonTaskTests.java
Labels: enhancement

#47 44 subissue 24 finish data persistence including encryption
  src/main/java/Main.java
  src/main/java/UI/LoginUI.java
  src/main/java/config/CommonCryptograph.java
  src/main/java/config/Cryptograph.java
  src/main/java/config/DataStorageMalfunction.java
  src/main/java/config/UserStorage.java
  src/test/java/UserRegistrationTests.java
  src/test/java/UserStorageTests.java
  src/test/java/entity_layer/CommonTaskTests.java
Labels: enhancement

#53 TimeBlockManagerUI
  src/main/java/time_manager_UI/TimeBlockManagerUI.form
  src/main/java/time_manager_UI/TimeBlockManagerUI.java
Labels: enhancement

#55 49 subissue 25 create login use case
  src/main/java/Main.java
  src/main/java/UI/CreateAccountUI.java
  src/main/java/UI/LoginUI.java
  src/main/java/UI/UserRegistrationResponseFormatter.java
  src/main/java/config/CommonCryptograph.java
  src/main/java/config/Cryptograph.java
  src/main/java/config/PathManager.java
  src/main/java/config/UserDataStoreGateway.java
  src/main/java/config/UserStorage.java
  src/main/java/entity_factories/CommonUser.java
  src/main/java/entity_factories/CommonUserFactory.java
  src/main/java/entity_layer/InMemoryUser.java
  src/main/java/use_cases/login/LoginController.java
  src/main/java/use_cases/login/LoginException.java
  src/main/java/use_cases/login/LoginInputBoundary.java
  src/main/java/use_cases/login/LoginInteractor.java
  src/main/java/use_cases/login/LoginRequest.java
  src/main/java/use_cases/user_registration/UserRegistrationController.java
  src/main/java/use_cases/user_registration/UserRegistrationInputBoundary.java
  src/main/java/use_cases/user_registration/UserRegistrationInteractor.java
  src/main/java/use_cases/user_registration/UserRegistrationPresenter.java
  src/main/java/use_cases/user_registration/UserRegistrationResponse.java
  src/test/java/LoginTests.java
  src/test/java/UserRegistrationTests.java
  src/test/java/UserStorageTests.java
Labels: enhancement

#42 Took out dependency on curriculum entity
  src/main/java/complete_task/CompletedTaskModel.java
  src/main/java/complete_task/completeTaskController.java
  src/main/java/complete_task/completeTaskInputBoundary.java
  src/main/java/complete_task/completeTaskOutputBoundary.java
  src/main/java/complete_task/completeTaskPresenter.java
  src/main/java/complete_task/completeTaskUseCase.java
  src/main/java/entity_layer/CommonCurriculum.java
  src/main/java/entity_layer/Curriculum.java
  src/test/java/complete_task/completeTaskUseCaseTest.java
Labels: enhancement

#52 TaskTree Implementation
  src/main/java/Main.java
  src/main/java/entity_factories/CommonTaskTreeFactory.java
  src/main/java/entity_factories/CommonUserFactory.java
  src/main/java/entity_factories/TaskTreeFactory.java
  src/main/java/entity_factories/UserFactory.java
  src/main/java/entity_layer/CommonTaskTree.java
  src/main/java/entity_layer/CommonUser.java
  src/main/java/entity_layer/TaskTree.java
  src/main/java/use_cases/user_registration/UserRegistrationInteractor.java
  src/test/java/LoginTests.java
  src/test/java/UserRegistrationTests.java
  src/test/java/UserStorageTests.java
  src/test/java/complete_task/completeTaskUseCaseTest.java
  src/test/java/entity_layer/CommonTaskTreeTests.java
Labels: enhancement

#59 Made taskID attribute transient
  src/main/java/entity_layer/CommonTask.java
Labels: bug

#66 Updated the ReadMe to explain build reconfigs
  README.md
  src/main/java/tasktree_UI/TaskTreeUI.form
Labels: documentation

#61 Extended to central window as well as made it visible
  src/main/java/time_manager_UI/TimeBlockManagerUI.form
  src/main/java/time_manager_UI/TimeBlockManagerUI.java
Labels: enhancement

#68 Implemented CommonTimeBlock
  src/main/java/entity_factories/CommonTimeBlockFactory.java
  src/main/java/entity_factories/TimeBlockFactory.java
  src/main/java/entity_layer/CommonTimeBlock.java
  src/main/java/entity_layer/TimeBlock.java
  src/test/java/entity_layer/CommonTimeBlockTests.java
Labels: enhancement

#64 Add Task Use Case
  src/main/java/use_cases/add_task/AddTaskController.java
  src/main/java/use_cases/add_task/AddTaskInputBoundary.java
  src/main/java/use_cases/add_task/AddTaskModel.java
  src/main/java/use_cases/add_task/AddTaskOutputBoundary.java
  src/main/java/use_cases/add_task/AddTaskPresenter.java
  src/main/java/use_cases/add_task/AddTaskUseCase.java
  src/main/java/use_cases/complete_task/CompleteTaskController.java
  src/main/java/use_cases/complete_task/CompleteTaskInputBoundary.java
  src/main/java/use_cases/complete_task/CompleteTaskOutputBoundary.java
  src/main/java/use_cases/complete_task/CompleteTaskPresenter.java
  src/main/java/use_cases/complete_task/CompleteTaskUseCase.java
  src/main/java/use_cases/complete_task/CompletedTaskModel.java
Labels: documentation, enhancement

#70 Remaining backend entities
  src/main/java/entity_factories/CommonCurriculumFactory.java
  src/main/java/entity_factories/CommonScheduleFactory.java
  src/main/java/entity_factories/CommonTimeBlockManagerFactory.java
  src/main/java/entity_factories/CommonUserFactory.java
  src/main/java/entity_factories/CurriculumFactory.java
  src/main/java/entity_factories/ScheduleFactory.java
  src/main/java/entity_factories/TaskFactory.java
  src/main/java/entity_factories/TaskTreeFactory.java
  src/main/java/entity_factories/TimeBlockFactory.java
  src/main/java/entity_factories/TimeBlockManagerFactory.java
  src/main/java/entity_layer/CommonCurriculum.java
  src/main/java/entity_layer/CommonSchedule.java
  src/main/java/entity_layer/CommonTimeBlockManager.java
  src/main/java/entity_layer/CommonUser.java
  src/main/java/entity_layer/Curriculum.java
  src/main/java/entity_layer/Schedule.java
  src/main/java/entity_layer/TimeBlockManager.java
  src/main/java/entity_layer/User.java
  src/test/java/entity_factories/CommonCurriculumFactoryTests.java
  src/test/java/entity_layer/CommonCurriculumTests.java
  src/test/java/entity_layer/CommonScheduleTests.java
  src/test/java/entity_layer/CommonTaskTreeTests.java
  src/test/java/entity_layer/CommonTimeBlockManagerTests.java
Labels: enhancement

#67 Set Availability Use Case Implementation
  src/main/java/set_availability/SetAvailabilityController.java
  src/main/java/set_availability/SetAvailabilityInputBoundary.java
  src/main/java/set_availability/SetAvailabilityModel.java
  src/main/java/set_availability/SetAvailabilityOutputBoundary.java
  src/main/java/set_availability/SetAvailabilityPresenter.java
  src/main/java/set_availability/SetAvailabilityUseCase.java
Labels: enhancement

#78 75 bugfix simplify entity factories
  src/main/java/entity_factories/CommonScheduleFactory.java
  src/main/java/entity_factories/CommonTaskTreeFactory.java
  src/main/java/entity_factories/PrebuiltCurriculumFactory.java
  src/main/java/entity_factories/PrebuiltScheduleFactory.java
  src/main/java/entity_factories/TaskTreeFactory.java
  src/test/java/entity_layer/CommonTaskTreeTests.java
Labels: enhancement

#82 CreateCurriculum class skeletons
  src/main/java/use_cases/create_curriculum/CreateCurriculumController.java
  src/main/java/use_cases/create_curriculum/CreateCurriculumInputBoundary.java
  src/main/java/use_cases/create_curriculum/CreateCurriculumInteractor.java
  src/main/java/use_cases/create_curriculum/CreateCurriculumOutputBoundary.java
  src/main/java/use_cases/create_curriculum/CreateCurriculumPresenter.java
  src/main/java/use_cases/create_curriculum/CurriculumModel.java
Labels: enhancement

#84 CompleteTask Tests
  src/main/java/use_cases/complete_task/CompleteTaskUseCase.java
  src/test/java/complete_task/completeTaskUseCaseTest.java
Labels: enhancement
